In [74]:
import pandas as pd

pd.DataFrame

pandas.core.frame.DataFrame

## pd.Series
- one dimentional collection of element of similar data type
- similar to Numpy array
- dedicated index
- support different pandas methods

In [75]:
import pandas as pd

s = pd.Series([1,2,3,4,1],index=["a","b","c","d","e"])

print(f"mean  {s.mean()}".rjust(30," "))
print(f"standard deviation  {s.std():.2f}".rjust(30," "))
print(f"sum  {s.sum():.2f}".rjust(30," "))
print(f"mode  {s.mode()}".rjust(30," "))

                     mean  2.2
      standard deviation  1.30
                    sum  11.00
     mode  0    1
dtype: int64

## pd.DataFrame
- collection of Series 
- with dedicated common index
- support pandas methods
- its two dimension data collection like spreadsheet,SQL table

In [76]:
import pandas as pd
# to create Dataframe
# read files like Excel,CSV,tsv ...
# or we can use collection of list as a row
# or make use of dictionary where key act as column name and value act as rows


# 1. from files
df1 = pd.read_csv("./../csvFiles/automobile.csv")


# 2. collection of list as a row
df2 = pd.DataFrame([
                ["Sumit",12],
                ["Mayur",13]
            ],
            columns=["name","age"])


data= {
    "name" : ["Shivam","Omkar"],
    "age"  : [12,13]
}

df3 = pd.DataFrame(data)
df3

     name  age
0  Shivam   12
1   Omkar   13

In [77]:
df2

    name  age
0  Sumit   12
1  Mayur   13

In [78]:
df1.size    # total cell count in data frame

3075

In [79]:
df1.shape               # row and columns

(205, 15)

In [80]:
df1.columns             # columns list

Index(['symboling', 'normalized-losses', 'make', 'fuel-type', 'body-style',
       'drive-wheels', 'engine-location', 'width', 'height', 'engine-type',
       'engine-size', 'horsepower', 'city-mpg', 'highway-mpg', 'price'],
      dtype='object')

In [81]:
df1.columns =['symboling', 'normalizedLosses', 'make', 'fuelType', 'bodyStyle',
       'driveWheels', 'engineLocation', 'width', 'height', 'engineType',
       'engineSize', 'horsepower', 'cityMpg', 'highwayMpg', 'price']
# to rename all the column

In [82]:
df1.dtypes

symboling             int64
normalizedLosses     object
make                 object
fuelType             object
bodyStyle            object
driveWheels          object
engineLocation       object
width               float64
height              float64
engineType           object
engineSize            int64
horsepower           object
cityMpg               int64
highwayMpg            int64
price                 int64
dtype: object

In [83]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   symboling         205 non-null    int64
 1   normalizedLosses  205 non-null    object
 2   make              205 non-null    object
 3   fuelType          205 non-null    object
 4   bodyStyle         205 non-null    object
 5   driveWheels       205 non-null    object
 6   engineLocation    205 non-null    object
 7   width             205 non-null    float64
 8   height            205 non-null    float64
 9   engineType        205 non-null    object
 10  engineSize        205 non-null    int64
 11  horsepower        205 non-null    object
 12  cityMpg           205 non-null    int64
 13  highwayMpg        205 non-null    int64
 14  price             205 non-null    int64
dtypes: float64(2), int64(5), object(8)
memory usage: 24.2+ KB

In [84]:
df1.head()

,symboling,normalizedLosses,make,fuelType,bodyStyle,driveWheels,engineLocation,width,height,engineType,engineSize,horsepower,cityMpg,highwayMpg,price
0,3,?,alfa-romero,gas,convertible,rwd,front,64.1,48.8,dohc,130,111,21,27,13495
1,3,?,alfa-romero,gas,convertible,rwd,front,64.1,48.8,dohc,130,111,21,27,16500
2,1,?,alfa-romero,gas,hatchback,rwd,front,65.5,52.4,ohcv,152,154,19,26,16500
3,2,164,audi,gas,sedan,fwd,front,66.2,54.3,ohc,109,102,24,30,13950
4,2,164,audi,gas,sedan,4wd,front,66.4,54.3,ohc,136,115,18,22,17450

In [85]:
df1.tail()

,symboling,normalizedLosses,make,fuelType,bodyStyle,driveWheels,engineLocation,width,height,engineType,engineSize,horsepower,cityMpg,highwayMpg,price
200,-1,95,volvo,gas,sedan,rwd,front,68.9,55.5,ohc,141,114,23,28,16845
201,-1,95,volvo,gas,sedan,rwd,front,68.8,55.5,ohc,141,160,19,25,19045
202,-1,95,volvo,gas,sedan,rwd,front,68.9,55.5,ohcv,173,134,18,23,21485
203,-1,95,volvo,diesel,sedan,rwd,front,68.9,55.5,ohc,145,106,26,27,22470
204,-1,95,volvo,gas,sedan,rwd,front,68.9,55.5,ohc,141,114,19,25,22625

In [86]:
df1.make      # access the column with dot operation.      
              # conditions : column name should not contain special char or space

0      alfa-romero
1      alfa-romero
2      alfa-romero
3             audi
4             audi
          ...
200          volvo
201          volvo
202          volvo
203          volvo
204          volvo
Name: make, Length: 205, dtype: object

In [87]:
df1["bodyStyle"]       # to access column

0      convertible
1      convertible
2        hatchback
3            sedan
4            sedan
          ...
200          sedan
201          sedan
202          sedan
203          sedan
204          sedan
Name: bodyStyle, Length: 205, dtype: object

In [88]:
df1.index

RangeIndex(start=0, stop=205, step=1)

In [89]:
df1[["symboling","make"]]

     symboling         make
0            3  alfa-romero
1            3  alfa-romero
2            1  alfa-romero
3            2         audi
4            2         audi
..         ...          ...
200         -1        volvo
201         -1        volvo
202         -1        volvo
203         -1        volvo
204         -1        volvo

[205 rows x 2 columns]

In [90]:
df1["make"]=="volvo"            # if we apply condition for filter 
                                # it returns boolean array
                                # this boolean array can be trasfer to
                                #  df[] to get filtered rows

0      False
1      False
2      False
3      False
4      False
       ...
200     True
201     True
202     True
203     True
204     True
Name: make, Length: 205, dtype: bool

In [91]:
df1[ df1["make"]=="volvo" ]

,symboling,normalizedLosses,make,fuelType,bodyStyle,driveWheels,engineLocation,width,height,engineType,engineSize,horsepower,cityMpg,highwayMpg,price
194,-2,103,volvo,gas,sedan,rwd,front,67.2,56.2,ohc,141,114,23,28,12940
195,-1,74,volvo,gas,wagon,rwd,front,67.2,57.5,ohc,141,114,23,28,13415
196,-2,103,volvo,gas,sedan,rwd,front,67.2,56.2,ohc,141,114,24,28,15985
197,-1,74,volvo,gas,wagon,rwd,front,67.2,57.5,ohc,141,114,24,28,16515
198,-2,103,volvo,gas,sedan,rwd,front,67.2,56.2,ohc,130,162,17,22,18420
199,-1,74,volvo,gas,wagon,rwd,front,67.2,57.5,ohc,130,162,17,22,18950
200,-1,95,volvo,gas,sedan,rwd,front,68.9,55.5,ohc,141,114,23,28,16845
201,-1,95,volvo,gas,sedan,rwd,front,68.8,55.5,ohc,141,160,19,25,19045
202,-1,95,volvo,gas,sedan,rwd,front,68.9,55.5,ohcv,173,134,18,23,21485
203,-1,95,volvo,diesel,sedan,rwd,front,68.9,55.5,ohc,145,106,26,27,22470
204,-1,95,volvo,gas,sedan,rwd,front,68.9,55.5,ohc,141,114,19,25,22625

In [92]:
df1[ (df1["make"]=="volvo") & (df1["bodyStyle"] == "wagon") ]

,symboling,normalizedLosses,make,fuelType,bodyStyle,driveWheels,engineLocation,width,height,engineType,engineSize,horsepower,cityMpg,highwayMpg,price
195,-1,74,volvo,gas,wagon,rwd,front,67.2,57.5,ohc,141,114,23,28,13415
197,-1,74,volvo,gas,wagon,rwd,front,67.2,57.5,ohc,141,114,24,28,16515
199,-1,74,volvo,gas,wagon,rwd,front,67.2,57.5,ohc,130,162,17,22,18950

In [93]:
df1.query(" make=='volvo' and `bodyStyle`=='wagon' ")     # single quote for value
                                                        # backtick for column name

,symboling,normalizedLosses,make,fuelType,bodyStyle,driveWheels,engineLocation,width,height,engineType,engineSize,horsepower,cityMpg,highwayMpg,price
195,-1,74,volvo,gas,wagon,rwd,front,67.2,57.5,ohc,141,114,23,28,13415
197,-1,74,volvo,gas,wagon,rwd,front,67.2,57.5,ohc,141,114,24,28,16515
199,-1,74,volvo,gas,wagon,rwd,front,67.2,57.5,ohc,130,162,17,22,18950

In [94]:
m = "volvo"
bs = "wagon"
df1.query(" make == @m and `bodyStyle` == @bs ")     # @ for local variable

,symboling,normalizedLosses,make,fuelType,bodyStyle,driveWheels,engineLocation,width,height,engineType,engineSize,horsepower,cityMpg,highwayMpg,price
195,-1,74,volvo,gas,wagon,rwd,front,67.2,57.5,ohc,141,114,23,28,13415
197,-1,74,volvo,gas,wagon,rwd,front,67.2,57.5,ohc,141,114,24,28,16515
199,-1,74,volvo,gas,wagon,rwd,front,67.2,57.5,ohc,130,162,17,22,18950

## loc[start:stop:step,start:stop:step]
- it is use to filter the dataframe in both direction 
- first portion is for index(row)
- second portion is for column

In [95]:
df1.loc[100:110:2,"symboling":"width":2]

     symboling    make  bodyStyle engineLocation
100          0  nissan      sedan          front
102          0  nissan      wagon          front
104          3  nissan  hatchback          front
106          1  nissan  hatchback          front
108          0  peugot      sedan          front
110          0  peugot      wagon          front

In [96]:
# df1.iloc[100:110:2,::]
df1.drop(df1[ df1["make"]=="nissan" ].index).iloc[100:110:2,0:4:2]

     symboling      make
118          1  plymouth
120          1  plymouth
122          1  plymouth
124          3  plymouth
126          3   porsche

In [97]:
df1.iloc[0:3,2] = "Hihi"         # allow modification

In [98]:
df1["make"][0:3] = "Huhu"         # doesn't allow modification with this kind of filter

/var/folders/tn/6j9xy4y51cnbfstw_b9jl9mr0000gn/T/ipykernel_41815/3234659207.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1["make"][0:3] = "Huhu"         # doesn't allow modification with this kind of filter

In [99]:
df1.iloc[0:3,2] = "alfa-romero"

In [100]:
df1.head(7)

,symboling,normalizedLosses,make,fuelType,bodyStyle,driveWheels,engineLocation,width,height,engineType,engineSize,horsepower,cityMpg,highwayMpg,price
0,3,?,alfa-romero,gas,convertible,rwd,front,64.1,48.8,dohc,130,111,21,27,13495
1,3,?,alfa-romero,gas,convertible,rwd,front,64.1,48.8,dohc,130,111,21,27,16500
2,1,?,alfa-romero,gas,hatchback,rwd,front,65.5,52.4,ohcv,152,154,19,26,16500
3,2,164,audi,gas,sedan,fwd,front,66.2,54.3,ohc,109,102,24,30,13950
4,2,164,audi,gas,sedan,4wd,front,66.4,54.3,ohc,136,115,18,22,17450
5,2,?,audi,gas,sedan,fwd,front,66.3,53.1,ohc,136,110,19,25,15250
6,1,158,audi,gas,sedan,fwd,front,71.4,55.7,ohc,136,110,19,25,17710

# EDA
<pre>
1.	Null Value (if null count <50%, else contact client)
a.	Median is best (avoid outliers)
b.	Mean
c.	Mode (if data is non-numeric)


2.	Duplicate Rows


3.	Outlier
a.	Box plot
b.	Z score (value should lie between -3 and +3)


4.	Label Encoder and one-hot encoder


5.	Distribution (skewness)
a.	Transformation(squreroot,sin,cos,log1p)


6.	Features Scaling
a.	Standard Scaler
b.	Min Max scaler(eg. Rating)


7.	Feature Engineering

In [101]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [102]:
df1 = pd.read_csv("./../csvFiles/automobile.csv")
df1.columns =['symboling', 'normalizedLosses', 'make', 'fuelType', 'bodyStyle',
       'driveWheels', 'engineLocation', 'width', 'height', 'engineType',
       'engineSize', 'horsepower', 'cityMpg', 'highwayMpg', 'price']

In [103]:
# pd.set_option("display.max_rows",None)
# pd.set_option("display.max_columns",None)

In [104]:
df1.head()

,symboling,normalizedLosses,make,fuelType,bodyStyle,driveWheels,engineLocation,width,height,engineType,engineSize,horsepower,cityMpg,highwayMpg,price
0,3,?,alfa-romero,gas,convertible,rwd,front,64.1,48.8,dohc,130,111,21,27,13495
1,3,?,alfa-romero,gas,convertible,rwd,front,64.1,48.8,dohc,130,111,21,27,16500
2,1,?,alfa-romero,gas,hatchback,rwd,front,65.5,52.4,ohcv,152,154,19,26,16500
3,2,164,audi,gas,sedan,fwd,front,66.2,54.3,ohc,109,102,24,30,13950
4,2,164,audi,gas,sedan,4wd,front,66.4,54.3,ohc,136,115,18,22,17450

In [105]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   symboling         205 non-null    int64
 1   normalizedLosses  205 non-null    object
 2   make              205 non-null    object
 3   fuelType          205 non-null    object
 4   bodyStyle         205 non-null    object
 5   driveWheels       205 non-null    object
 6   engineLocation    205 non-null    object
 7   width             205 non-null    float64
 8   height            205 non-null    float64
 9   engineType        205 non-null    object
 10  engineSize        205 non-null    int64
 11  horsepower        205 non-null    object
 12  cityMpg           205 non-null    int64
 13  highwayMpg        205 non-null    int64
 14  price             205 non-null    int64
dtypes: float64(2), int64(5), object(8)
memory usage: 24.2+ KB

## Step 1: Null Value

In [ ]:
selected = df1[df1["normalizedLosses"]=="?"].index

df1.loc[selected,"normalizedLosses"] = "0"

# df1["normalized-losses"] = df1["normalized-losses"].replace("?",0).astype(int)
df1["normalizedLosses"]=df1["normalizedLosses"].astype("int")

# df["normalized-losses"] = df["normalized-losses"].replace(0,df["normalized-losses"].median())
df1.loc[selected,"normalizedLosses"] = df1["normalizedLosses"].median()

In [108]:
df1.head()

,symboling,normalizedLosses,make,fuelType,bodyStyle,driveWheels,engineLocation,width,height,engineType,engineSize,horsepower,cityMpg,highwayMpg,price
0,3,103,alfa-romero,gas,convertible,rwd,front,64.1,48.8,dohc,130,111,21,27,13495
1,3,103,alfa-romero,gas,convertible,rwd,front,64.1,48.8,dohc,130,111,21,27,16500
2,1,103,alfa-romero,gas,hatchback,rwd,front,65.5,52.4,ohcv,152,154,19,26,16500
3,2,164,audi,gas,sedan,fwd,front,66.2,54.3,ohc,109,102,24,30,13950
4,2,164,audi,gas,sedan,4wd,front,66.4,54.3,ohc,136,115,18,22,17450

In [109]:
df1["horsepower"] = df1["horsepower"].replace("?",0).astype(int)
df1["horsepower"] = df1["horsepower"].replace(0,df1["horsepower"].median())

In [110]:
df1.describe()

,symboling,normalizedLosses,width,height,engineSize,horsepower,cityMpg,highwayMpg,price
count,205.000000,205.00000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000
mean,0.834146,118.20000,65.907805,53.724878,126.907317,104.165854,25.219512,30.751220,13227.478049
std,1.245307,32.58419,2.145204,2.443522,41.642693,39.529733,6.542142,6.886443,7902.651615
min,-2.000000,65.00000,60.300000,47.800000,61.000000,48.000000,13.000000,16.000000,5118.000000
25%,0.000000,101.00000,64.100000,52.000000,97.000000,70.000000,19.000000,25.000000,7788.000000
50%,1.000000,103.00000,65.500000,54.100000,120.000000,95.000000,24.000000,30.000000,10345.000000
75%,2.000000,137.00000,66.900000,55.500000,141.000000,116.000000,30.000000,34.000000,16500.000000
max,3.000000,256.00000,72.300000,59.800000,326.000000,288.000000,49.000000,54.000000,45400.000000

In [111]:
df1.describe(include=object)          # str

          make fuelType bodyStyle driveWheels engineLocation engineType
count      205      205       205         205            205        205
unique      22        2         5           3              2          7
top     toyota      gas     sedan         fwd          front        ohc
freq        32      185        96         120            202        148

## Step 2: Drop Duplicates

In [112]:
df1.drop_duplicates(inplace=True)

In [113]:
df1.shape

(205, 15)

## Step 3 : Remove Outlier

In [120]:
df1.select_dtypes(exclude=object).head()

,symboling,normalizedLosses,width,height,engineSize,horsepower,cityMpg,highwayMpg,price
0,3,103,64.1,48.8,130,111,21,27,13495
1,3,103,64.1,48.8,130,111,21,27,16500
2,1,103,65.5,52.4,152,154,19,26,16500
3,2,164,66.2,54.3,109,102,24,30,13950
4,2,164,66.4,54.3,136,115,18,22,17450

In [122]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()      # Z score
val = sc.fit_transform(df1.select_dtypes(exclude=object))

In [126]:
((val>3) & (val<-3)).sum()

np.int64(0)